### ISSUE TITLE
Transaction not apear in QbitNinja

### ISSUE THREAD

**Issue by jrmaciel** [MetacoSA/QBitNinja#27]
I transfered a amount in QbitNinja e the amount not apear in my wallet, but apear in blockchain

Transaction ID
9278239761d2c61bd165f52f7812743fa1b44e5bb01a4ebfe5a8bb1a45bff039

https://blockchain.info/tx/9278239761d2c61bd165f52f7812743fa1b44e5bb01a4ebfe5a8bb1a45bff039

**Comment by NicolasDorier** [comment]
thanks a lot, it seems that qbit ninja is left behind now. Checking that

**Comment by NicolasDorier** [comment]
My indexer indeed crashed. It is catching up the chain now

**Comment by jrmaciel** [comment]
Thanks, see that 
http://api.qbit.ninja/balances/16PJRSdDTDaxrUBXqgqvjmy8QNUoijHS8U
not found in qbit

but in blockchain
https://blockchain.info/address/16PJRSdDTDaxrUBXqgqvjmy8QNUoijHS8U

my balance not apear in my wallet and can't tranfer btc

**Comment by NicolasDorier** [comment]
it appears now, as I said, it was catching up.

**Comment by james1278** [comment]
Hi, I have installed Qbitninja client package in my c# project.
Now i am trying to send transaction on Testnet, but could not see those transaction using following code.
My question:

do we need to add or install anything else on server?
Do we need qbitninja.server?
Do we need azure server or it can run on any pc?
If possible then please provide sample code.
What fee we need to used? because i tried 0.0004 as well as .0015.
public void SendCoin(string receiverAdress, decimal amount, string message = null)
{
BitcoinSecret secretPrivateKey = masterKey.ExtKey.Derive(1).PrivateKey.GetWif(network);
var cl = new List();
Money minerFee = new Money(0.0004m, MoneyUnit.BTC);
var transaction = new Transaction();

		Money currrentBalance = new Money(0, MoneyUnit.BTC);
		var historyTransaction = client.GetBalance(secretPrivateKey.ScriptPubKey, true).Result;
		foreach (var tx in historyTransaction.Operations)
		{
			currrentBalance += tx.Amount;
			foreach (var coin in tx.ReceivedCoins)
			{
				cl.Add(coin);
				transaction.Inputs.Add(new TxIn(coin.Outpoint, secretPrivateKey.ScriptPubKey));
			}
		}				
		
		// calculate what amount of bitcoin needed to be send
		Money receiverAmount = new Money(amount, MoneyUnit.BTC);
		Money changeBackAmount = currrentBalance - receiverAmount - minerFee;

		// make sure you have enough money
		var totalSpendAmount = amount + minerFee.ToDecimal(MoneyUnit.BTC);
		if (totalSpendAmount > currrentBalance.ToDecimal(MoneyUnit.BTC))
			throw new Exception("The total spend amount is greater than you have now");

		// add outputs to tx
		Script receiverScriptPubKey;
		receiverScriptPubKey = new BitcoinPubKeyAddress(receiverAdress).ScriptPubKey;

		TxOut txOut = new TxOut()
		{
			Value = receiverAmount,
			ScriptPubKey = receiverScriptPubKey
		};
		TxOut changeBackTxOut = new TxOut()
		{
			Value = changeBackAmount,
			ScriptPubKey = secretPrivateKey.ScriptPubKey
		};

		transaction.Outputs.Add(txOut);
		transaction.Outputs.Add(changeBackTxOut);


		// add message
		if (!String.IsNullOrWhiteSpace(message))
		{
			var bytes = Encoding.UTF8.GetBytes(message);
			transaction.Outputs.Add(new TxOut()
			{
				Value = Money.Zero,
				ScriptPubKey = TxNullDataTemplate.Instance.GenerateScriptPubKey(bytes)
			});
		}

		// Sign the transaction
		transaction.Sign(secretPrivateKey, false);

		// Broadcast your transaction to all miners
		BroadcastResponse broadcastResponse = client.Broadcast(transaction).Result;
		if (!broadcastResponse.Success)
			throw new Exception(broadcastResponse.Error.Reason);
	}
===================================================================
This is your Reply
----------------

So by default you are using public server, you don't need yours.If you want yours, yet the indexer need to be hosted on azure. The front end does not matter too much.This is not well documented, but with the README.md and some .NET knowledge, it should not be difficult to host yourself (in azure).QBitNinja does not expose fees, you will need to depends on another system to get it (bitcoinfees has a simple json API for it).QBItNinja broadcast sometimes is a bit buggy or does not give you big details about why your transaction is rejected. You can try to print transaction.ToHex() then use https://www.smartbit.com.au/txs/pushtx to push it, it will give you better info.Also, you should use NBitcoin TransactionBuilder for creating transactions, it catches most of error for you before even broadcasting. (this is documented in the book)
--

==========================================================
and after out question.
==================
Thanks Nicolas,
But we are doing testing TestNet Transaction and after we checking here that time getting like this error "Nbitcoin + No coin matching was found"

see this
Transaction id : 769532910c1a85b805a84c88fb6c29961f0e789aa78a4b98401cbca03c2a9f61
My ID : mpLym6uutZBqiKhiYnejfHkiMU2QYsfGPt
Sending To This : mztqvWDhMzxYrJdBXuXGVEkpf5JwbGJkEY
Transaction hex: 0100000001619f2a3ca0bc1c40984b8aa79a780e1f96296cfb884ca805b8851a0c91329576000000006b483045022100adbde78d20682984a83aa5c84b24bb9e981e3758563c0b2f6e57ed888a4ec10e02204bf2a521d1cb8de9089686d0f04ec0ac6f05d9d4b1a2140f04db0f97cfab3aae012102c53763fb012a51da97f08b55aa51cf14fada83edcdaa4f28bcac960a5678a1b0ffffffff0220aa4400000000001976a914d48e38ec4f64c30e6ed6487cac6528a25ecfa56d88ac107a0700000000001976a91460d6324d255521b63814975710eaca545be3db6488ac00000000

so please can you suggest me for same we can solve it.

https://live.blockcypher.com/btc-testnet/tx/769532910c1a85b805a84c88fb6c29961f0e789aa78a4b98401cbca03c2a9f61/

**Comment by NicolasDorier** [comment]
Can you try again, the testnet qbitninja was out of sync, I neeeded to manually start again.

**Comment by james1278** [comment]
Hi Nicolas,
When i tried with 58a0d4bd43ee147d56a192be4b289a12210219b19b7d8fb4afe7099fccad5321 and 909812c386089733ddff34e806a821f72c943e7f4d000d415cda91a0ba6f21c6 transaction, it is working and sending the btc against above transaction. But when i check this using  
 var builder = new TransactionBuilder();
            NBitcoin.Policy.TransactionPolicyError[] error = null;
            Console.WriteLine(builder.Verify(transaction,out error));

Then it shows me no matching coin. But then also it was broadcast properly on testnet server. So how we verify the transaction in code? 

is it working for live transaction(Mainnet)? Is there any lagging issue for Main network? because i am rely on your server only.

**Comment by NicolasDorier** [comment]
For `builder.Verify` to work, you need to AddCoins first...

**Comment by james1278** [comment]
I have already added coin for above given transaction but it do not work. but then also it was broadcast on server.
I am using Qbitninja version 3.39 with nbitcoin version 38.

so is this any version issue or this can resolved with live Main network?

**Comment by NicolasDorier** [comment]
please copy paste all your code where you are doing the Verify...

**Comment by james1278** [comment]
public void SendCoinOld(string receiverAdress, decimal amount, string message = null)
        {
            BitcoinSecret secretPrivateKey = masterKey.ExtKey.Derive(1).PrivateKey.GetWif(network);
            // set default parameters
            decimal fee =  0.0004m;//GetFee();

            var masterPubKey = this.masterPubKey.ExtPubKey;
            var result = new SendCoinResult
            {
                Inputs = new List<int>()
            };


            // find most suitable transaction
            decimal currentAmount = amount + fee;

            //var senderKey = new BitcoinPubKeyAddress("mmcGZsK8X3gCjFXYPCXe41yKPrqafUeUyo").ScriptPubKey;
            var historyTransaction = client.GetBalance(secretPrivateKey.ScriptPubKey, true).Result;
            // create transaction
            var transaction = new Transaction();
            var coinList = new List<ICoin>();

            // add inputs to tx
            decimal currentBalanceDecimal = 0;
            //foreach (var tx in historyTransaction.Operations)
            //{

            
            GetTransactionResponse currentTx = client.GetTransaction(new uint256("36a5fb9edb3099ca7be754d10ed9f711d40be9f7460b6953201f0ce42ecf4f42")).Result;
            //GetTransactionResponse currentTx = client.GetTransaction(new uint256("769532910c1a85b805a84c88fb6c29961f0e789aa78a4b98401cbca03c2a9f61")).Result;

            foreach (var coin in currentTx.ReceivedCoins)
                if (((Money)coin.Amount).Satoshi > 0
                    && coin.CanGetScriptCode
                    && coin.GetScriptCode() == secretPrivateKey.ScriptPubKey
                    )
                {
                    currentBalanceDecimal += ((NBitcoin.Coin)coin).Amount.ToDecimal(MoneyUnit.BTC);
                    coinList.Add(coin);
                    transaction.Inputs.Add(new TxIn(coin.Outpoint, secretPrivateKey.ScriptPubKey));
                }
            // }
            //-----------


            // calculate what amount of bitcoin needed to be send
            Money currrentBalance = new Money(currentBalanceDecimal, MoneyUnit.BTC);
            Money minerFee = new Money(fee, MoneyUnit.BTC);
            Money receiverAmount = new Money(amount, MoneyUnit.BTC);
            Money changeBackAmount = currrentBalance - receiverAmount - minerFee;

            Script receiverScriptPubKey = new BitcoinPubKeyAddress(receiverAdress).ScriptPubKey;

            transaction.Outputs.Add(new TxOut
            {
                Value = receiverAmount,
                ScriptPubKey = receiverScriptPubKey
            });
            if (changeBackAmount > 0)
                transaction.Outputs.Add(new TxOut
                {
                    Value = changeBackAmount,
                    ScriptPubKey = secretPrivateKey.ScriptPubKey
                });
            else
                result.Output = null;

            // sign transaction
            var keys = new List<ExtKey>();
            keys.Add(masterKey.ExtKey.Derive((uint)1));

            transaction.Sign(keys.ToArray(), coinList.ToArray());

            var builder = new TransactionBuilder();
            NBitcoin.Policy.TransactionPolicyError[] error = null;
            Console.WriteLine(builder.Verify(transaction,out error));

            // Broadcast your transaction to all miners
            BroadcastResponse broadcastResponse = client.Broadcast(transaction).Result;
            if (!broadcastResponse.Success)
                throw new Exception(broadcastResponse.Error.Reason);

        }

**Comment by NicolasDorier** [comment]
That's what I said, in your example you did not passed coins to the builder with `builder.AddCoins`

**Comment by james1278** [comment]
Thanks for reply. I thought if i add that during transaction sign then it will work. now it is verified transaction.

Just quick question:
1. Is there any downtime for main network? Means i can work only with your server without any issue. is it correct?
2. Can i get the list of memonic word for our dll?
3. Do we need to create any account to use Live main network?

**Comment by FarhadYazdi** [comment]
http://api.qbit.ninja/balances/1CK6KHY6MHgYvmRQ4PAafKYDrg1ejbH1cE/summary
Not answering, Even with the code

and balance of addresses with mined block is not correct
http://api.qbit.ninja/balances/1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa/summary
shows -> "amount": 1809533767 but final balance is 68.10533767BTC, mined BTC not showing
